.github/CODEOWNERS

We've open sourced the repos now, so the CODEOWNERS file is actually working and adding reviewers to things. But that does sadly mean we have to say a tearful goodbye to @contolini from the file. 😢
- removed @contolini 
- adds @billhimmelsbach 
- adds a little sadness
1. Are you named Chris Contolini and will you see less random PRs pop up in your notifications?
- thanks for your work @contolini! 🎉

chore(git): remove @contolini in codeowners

---

src/pages/Filing/FilingHome.tsx

Adjusts spacing and adds a divider as per [this design feedback](https://github.com/cfpb/sbl-frontend/issues/192).
Closes: https://github.com/cfpb/sbl-frontend/issues/192
- Adds a divider with 45px above and below between the button and the numbered icon list
- Increases space between the heading and the list items to 30px
1. Does this page more closely resemble [the designs here](https://github.com/cfpb/sbl-frontend/issues/192)?
- The original ticket has a possible additional task:
```
(Possibly) Increase the space after the numbered icon list to 45px (between the list and the well)
```
On inspection, it appears that the space between these two elements is already 45px. Happy to change stuff though if we want to! 👍

fix(Unauthenticated): adjust heading spacing, add divider

---

src/pages/Filing/InstitutionDetails/IdentifyingInformation.tsx
src/pages/ProfileForm/types.ts

support change from `sbl_institution_type` to `sbl_institution_types` as an array of user chosen institution types
closes: #180 
- create a string from `sbl_institution_types` names
1. Does the "Type of financial institution" now render on the "View your financial institution profile" page instead of just rendering "Not available"?
**Before**
**After**
- I think the seed data is out of date when it comes to institutions with type "Other". I pinged Le over [on this issue](https://github.com/cfpb/sbl-frontend/issues/137#issuecomment-1918230517) about it.

fix(institution-details): allow institution type array

---

src/api/requests/fetchIsDomainAllowed.ts

It looks like there was an issue in the endpoint url `fetchIsDomainAllowed` during the axios transition, so this fixes that endpoint.
- Change url for `fetchIsDomainAllowed` back to : `/v1/institutions/domains/allowed?domain=${domain}`,
1. Can users now be denied based on the their email domain?
- Maybe take a quick peek at the [other axios changes](https://github.com/cfpb/sbl-frontend/pull/207/files) just to make sure?
- Looking forward to building out some cypress tests to catch these regressions 👍

fix(fetchIsDomainAllowed) fix endpoint url

---

src/pages/ProfileForm/index.tsx

After the latest merges, I can still sometimes get users with denied email domains hitting SBL Help even [after fixing the endpoint](https://github.com/cfpb/sbl-frontend/pull/231). This little logic check should make sure that never happens. Should be better too for future devs who want to move around these logic blocks in the future.
- add a check to make absolutely sure that users with blocked emails are not redirected to SBL Help
1. If a user has a denied domain, then they cannot be directed to SBL Help
- gonna prioritize getting those cypress tests in to check these use cases

fix(profile-form): never let a denied domain hit sbl help

---

README.md
package.json
start.sh

Updates the start script with the new repos and also provides an easier way to update all the dependent repos.
Closes: #264
- add new repos: [regtech-mail-api](https://github.com/cfpb/regtech-mail-api) and [sbl-filing-api](https://github.com/cfpb/sbl-filing-api)
- add `yarn update` (happy to change the name) to checkout all the dependent repos into `main` and pull the latest changes
- adds `set -e` to catch errors if a command exits with a non-zero status that doesn't have explicit error handling
- remove `docker pull` line that has been erroring out silently for awhile
1. Does `yarn start` work normally?
2. Does `yarn update` checkout each repo to `main`, pull the latest, and then start up the containers normally?
_Example `yarn update` run_
_Error handling example with `set -e`: if …

feat(start.sh): add new repos, add update command, fail on error

---

src/api/axiosService.ts
src/api/common.ts
src/api/requests/submitUpdateFinancialProfile.ts
src/api/requests/submitUserProfileFi.ts

Updates the headers according [to this PR](https://github.com/cfpb/regtech-mail-api/pull/23) and prior discussions yesterday about the email-to-case system.
We're no longer setting the whole subject, just giving the backend what type of case we want to create.
Closes: #280 
- email subject -> case type
1. You saw it in the demo! 🎉

feat(email-to-case): adjust for new header: case-type

---

src/App.tsx
src/pages/Filing/FilingApp/FilingOverviewPage.tsx
src/pages/Filing/PaperworkNotice.tsx
src/pages/Filing/PrivacyNotice.tsx
src/pages/Filing/UpdateFinancialProfile/UfpForm.tsx
src/pages/Filing/ViewInstitutionProfile/index.tsx
src/pages/Filing/ViewUserProfile/index.tsx
src/pages/ProfileForm/index.tsx
src/pages/Summary/Summary.tsx

**Note: same as https://github.com/cfpb/sbl-frontend/pull/360, but now merging on main**
Currently we don't have skip links that aid in making our content accessible to those using tab navigation.
Closes: #359 
- adds skip link to App.tsx
- adds missing `id="main"` to pages that still need it
1. Can you press `tab` then `enter` to skip to the main content of a page in the tab order? (Try pressing `tab` again to confirm.
- the skip link could be a little fancier with its CSS transition like on cf.gov, but we're prioritizing [just the accessibility first](https://github.com/cfpb/design-system-react/pull/330)
- works in conjunction with https://github.com/cfpb/design-system-react/pull/330 for the focus ring

feat(skip-links): add skip link and main id to missing pages

---

src/pages/Filing/UpdateFinancialProfile/UfpForm.tsx
src/pages/Filing/UpdateFinancialProfile/UpdateAffiliateInformation.tsx
src/pages/Filing/UpdateFinancialProfile/UpdateIdentifyingInformation.tsx

Closes #379
- Make RSSD input fields `type='text'` to remove increment/decrement arrows
- Add workaround to keep displayed field value in sync with RHF data store
1. Visit Update institution profile page
2. Try to enter non-numbers in an RSSD ID field
3. Verify that the increment/decrement arrows are not displayed when the field is focused
- @natalia-fitzgerald Very large numbers cause the input value to be oddly parsed (ex. `2142333345222222311111` becomes `2.1423333452222224e+21`).  I couldn't find a definition online of RSSD ID that explains any restrictions or limits on length/size, so we'll need to follow up with the data folks for further guidance here.

fix: Update Institution profile - Make RSSD inputs text (remove arrows)

---

src/components/InputEntry.tsx
src/pages/Filing/UpdateFinancialProfile/UfpForm.tsx
src/pages/Filing/UpdateFinancialProfile/UpdateAffiliateInformation.tsx
src/pages/Filing/UpdateFinancialProfile/UpdateIdentifyingInformation.tsx
src/pages/Filing/formHelpers.ts
tailwind.config.js

Closes #377
- feat: Add `helperText` to `<InpuEntry>`
- feat: Add `labelHelper` color to Tailwind config
- task: Add helper text to Update Institution profile's RSSD, LEI, and TIN fields
- task: Reorders display of RSSD fields

feat: InputEntry - Support optional helper text

---

src/api/requests/submitPointOfContact.ts
src/pages/Filing/FilingApp/FilingContact.tsx
src/pages/PointOfContact/index.tsx
src/pages/ProfileForm/ProfileFormUtils.ts
src/types/filingTypes.ts
src/types/formTypes.ts

Closes #416 
- Integrates form into workflow
- Enables saving POC info to API
- Populates form with existing POC contact when available
- Only saves data to API if it has changed
What we see:
- User populates form data
- Form validates content and displays an error for missing/malformed fields
- On initial successful submit the data is sent to the API and user is routed to next step
- When revisiting the POC page, contact info from the Filing API is pre-populated in the form
- On second submit, when no data has changed, no API call is made
https://github.com/cfpb/sbl-frontend/assets/2592907/d7e7b851-ef40-4600-ae57-13adcbc655b0

Point of Contact - Phase 1

---

src/pages/Filing/FilingApp/FilingSubmit.tsx

Close #564 
- Removes the double underline on the `email our support staff` link
|Before|After|
|---|---|
|<img width="734" alt="Screenshot 2024-05-22 at 10 07 18 AM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/46c49fea-232d-4eef-a735-212660d02a6a">|<img width="732" alt="Screenshot 2024-05-22 at 10 07 27 AM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/1689fe16-3d20-4106-bdd7-c5df8f6e9740">|

fix: [Sign & submit] Fix link double-underline

---

src/pages/AuthenticatedLanding/ReviewInstitutions.tsx

Close #648 
- Updates alert to be form-level and to include email link
1. Force [this line](https://github.com/cfpb/sbl-frontend/pull/649/files#diff-b9b9bcc791f1f8ebbb7941cf10f99a41746a32ca2282c4a9c870e599ea6ca62bR17) to be `if (true)`
2. Visit `/landing` page
3. Confirm alert matches design file

fix(Filing home): Render error alert when cannot load associated institutions

---

src/components/InputEntry.tsx
src/components/LabelOptional.tsx
src/components/StepIndicator.tsx
tailwind.config.js

Close #612 
- Add Tailwind variables for DS colors: gray20, navy
- Adjust step font weights (all medium[500])
- Remove poorly named Tailwind color variables
|When|Shot|
|---|---|
|Before|<img width="1237" alt="Screenshot 2024-06-03 at 12 53 05 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/f184996a-2129-4cd5-89c7-279bc5530d25">|
|After|<img  alt="Screenshot 2024-06-03 at 12 44 41 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/20cbef1d-c66a-4bf1-823c-23942a362bea">|

Step Indicator styles

---

src/pages/Filing/UpdateFinancialProfile/TypesFinancialInstitutionSection.tsx
src/pages/TypesFinancialInstitutions/index.tsx

**Part of the clearance review**
Updates Type of financial institution to latest content based on pre-clearance review of the filing app.
This does partly depend on PR #663 since it won't look exactly like figma without it.
Closes #661 
- Pre-clearance -- Update intro body text link and double check rest of body content in the intro
- Pre-clearance -- Add helper text to "Type of financial institution" field set
**This does partly depend on PR https://github.com/cfpb/sbl-frontend/pull/663 since it won't look exactly like figma without it.**
|Before|After|
|---|---|
|![Before](https://github.com/cfpb/sbl-frontend/assets/19983248/836e8b25-5e99-40df-94c1-4ddeb890b331)|![After](https://github.com/cfpb/sbl-frontend/assets/19983248/81563b78-9a04-494e-92e1-fecd2f221521)|
|Before|After|
|---|---| …

fix(type-of-fi): update content for clearance

---

src/pages/Filing/FilingApp/InstitutionCard.helpers.ts

**Part of the clearance review**
Updates to latest content based on pre-clearance review of the filing app.
I've added a test account to `sbl-test-accounts` to see all the different states for the filing home on the preview site at once, just contact me for the details if necessary.
Closes #659 
- Pre-clearance --- Update body text in "Upload your lending data" card
- Pre-clearance --- Update body text in "Resolve errors in your lending data" card
- Pre-clearance --- Update body text in "Provide point of contact" card
|Before|After|
|---|---|
|![Before](https://github.com/cfpb/sbl-frontend/assets/19983248/78cf5fb8-f3c6-4e33-8c9a-5f1fefb459d5)|![After](https://github.com/cfpb/sbl-frontend/assets/19983248/7ef8a47f-807f-4215-8450-06d99409437f)|
|Before|After|
|---|---| …

fix(filing-home): update content for clearance

---

src/App.tsx

We were seeing testers during bug bashes hit 403s when sitting on the upload page for more than 10 minutes. This is a hotfix meant to fix this bug for the beta / next bug bash on Friday, but the react-oidc-context library will be revisited after launch. A lot of people have this issue it seems when users idle on a page, with the most common approach being to pop up an alert or use the approach I do in this PR: silently renewing the tokens if they expire. I'd rather lean on just automaticSilentRenew, and I think it may work in later versions of the library if we upgraded, but I'd like to fix it for now for the next bug bash then do a more thorough look at the automaticSilentRenew behavior when we get more time.
The obvious problem with this implementation is that currently this causes a …

fix(auth): silent renew auth token between refreshes

---

src/api/requests/fetchFilingSubmissionLatest.ts
src/utils/constants.ts
src/utils/useUploadMutation.tsx

At the bug bash on Wednesday, we decided to:
- re-enable the exponential backoff
- the frontend should retry on the assortment of 500s, 400s, etc, particularly for anything related to uploading files
1. re-enable the exponential backoff
re-enabled the code, removed the comment since we can use @shindigira's `MAX_RETRY_DELAY` instead.
2. the frontend should retry on the assortment of 500s, 400s, etc, particularly for anything related to uploading files
#711 adds retries to useQueries that were missing it, but when I was testing it last night, the `/submissions` POST was erroring out with some regularity.
This particular POST isn't a danger to retry on error: we're not in danger of putting the user into a weird state (just another submission as a worst case). But I did make a separate retry …

fix(upload): retry upload, reenable backoff

---

src/pages/Filing/FilingApp/FileSubmission.tsx

Close #725 
- If user has not yet submitted a file, the `Upload` button is primary and `Save and continue` is secondary
- Once an upload is completed, the `Upload` button is secondary and `Save and continue` is primary
https://github.com/cfpb/sbl-frontend/assets/2592907/1ef58157-000b-4153-ade2-b42f632e52f3

fix: [Upload] Style the Upload button as "secondary" once a user has completed an upload

---

Dockerfile
nginx-entrypoint.sh
nginx/nginx.conf

Re-enables env var injection, while still conforming to the evidence collection script (it appears running it only produces changes in timestamps).
- utilized the service account inside of the entrypoint, instead of switching to the service account when in the entrypoint
- disables the container bouncing feature for simpler permissions handling 
1. Does the evidence collection still pass, but now you can inject vars into the frontend?

fix(security): re-enable var injection

---

src/api/axiosService.ts
src/api/requests/fetchFilingSubmissionLatest.ts
src/utils/getOidcTokenOutsideContext.ts

Based on my testing, this fixes the remaining problems with 403s.
[This PR](https://github.com/cfpb/sbl-frontend/pull/738) updated the react-oidc-context library so that the iframe auth injection worked when `automaticSilentRenew` was enabled and let the token be updated in between page views without any re-renders.
Now we've got another problem that this PR fixes: react query. When the auth token gets refreshed, any query will continue to use the old auth token unless we add it to the `queryFn`. That totally works, but will cause a re-render unless we pepper the codebase with `useMemo`s and `useCallback`s, that I don't want to do until we upgrade to React 19 post-mvp and React Compiler [does it for us](https://react.dev/learn/react-compiler).
So where does that leave us? The internet …

fix(axios): keep auth token in sync with oidc token

---

index.html

We'll need to add the `nonce` tag to the [import-meta-env](https://import-meta-env.org/) script, otherwise it doesn't run in production.
- adds nonce to import-meta-env
- adjusts comment a bit to emphasize public env vars
1. Go onto the preview site and try to login. If it works, then this is working. 👍

fix(csp): adds nonce to import-meta-env script

---

src/pages/Filing/FilingApp/FileSubmission.tsx

Lift the max file size to 2gb for testing.
1. Change to `FILE_SIZE_LIMIT_2GB` from `FILE_SIZE_LIMIT_50MB`
- Can you upload bigger files now?

spike(upload): increase max upload size to 2gb

---

src/components/CommonLinks.tsx
src/components/Link.tsx
src/pages/Filing/FilingApp/FieldEntry.tsx
src/pages/Filing/FilingApp/FilingErrors/FilingErrorsAlerts.tsx
src/pages/Filing/FilingApp/FilingOverviewPage.tsx
src/pages/Filing/FilingApp/FilingWarnings/FilingWarningsAlerts.tsx
src/pages/Filing/FilingApp/InstitutionCard.tsx
src/pages/Filing/FilingHome.tsx
src/pages/ProfileForm/Step1Form/Step1FormHeader.tsx
src/pages/Summary/Summary.data.tsx

Close #779 
- Centralize logic to open external links in new tab
- Remove all explicit `target="_blank"`s
1. (internal) Visit authenticated landing page, click on an Institution in the `Review your FI profile` section; Should open in same tab
1. (external) Visit `Upload` page and click on the "filing instructions guide..." link, should open in new tab

Open external links in new tab

---

index.html
src/App.tsx
src/api/requests/downloadValidationReport.ts
src/components/BetaAndLegalNotice.tsx
src/components/FormErrorHeader.data.ts
src/pages/AuthenticatedLanding/ReviewInstitutions.tsx
src/pages/Filing/FilingApp/FilingSubmit.helpers.tsx
src/pages/Filing/FilingApp/FilingSubmit.tsx
src/pages/Filing/FilingApp/InstitutionCard.helpers.ts
src/pages/Filing/FilingHome.tsx
src/pages/Filing/PrivacyNotice.tsx
src/pages/PointOfContact/index.tsx
src/pages/ProfileForm/Step1Form/Step1FormInfoFieldGroup.tsx

We're making the name consistent across the website to a new name: "Small Business Lending Data Filing Platform." This also includes changing "submission" to "filing" in most contexts.
- Small Business Lending Data Submission Platform -> Small Business Lending Filing Platform
- index.html for title and meta info
- App.tsx
- BetaAndLegalNoice.tsx
- Privacy notice
- Point of contact
- Complete user profile
- Submission to Filing
- FormErrorHeader in point of contact form validation
- Review institution info
- Sign and Submit
- Post submission page (not implemented)
- Filing Home
- Point of contact
- "platform" to "beta platform" when referring directly to the beta in the beta/legal notice
- Remove "submission" from the report name and change hyphens to underscores
Currently on the dev …

fix(content): mostly change submission to filing

---

src/components/BetaAndLegalNotice.tsx
src/components/Loading.tsx

Closes #1003 
- BetaAndLegalNotice: Refactor to avoid passing the entire content of the notice via the `message` prop, which gets wrapped in a `<p>` in the DSR.
- Loading: Replace `<div>` with a `<span>`
1. Start SBL Frontend: `yarn start`
2. Verify Beta/Legal notice looks the same
- `git checkout main` => `git checkout -b 1003-x-cannot-be-child-of-p`
3. Verify Loading looks the same
- Visit http://localhost:8899/loading
- `git checkout main` => `git checkout -b 1003-x-cannot-be-child-of-p`
| Before | After|
|---|---|
|Beta/Legal<br/><br/>![BetaLegal-before](https://github.com/user-attachments/assets/f7b45df0-36c8-46e5-ad03-6ddd4c1528dc)|Beta/Legal<br/><br/>![BetaLegal-after](https://github.com/user-attachments/assets/6a30873e-a990-4920-b781-94cc0098346a)|
|[Loading Video: …

[fix] <X> cannot appear as a descendant of <p>

---

e2e/pages/filing-app/uploadFile/completeUploadLogicErrors.spec.ts

Closes #981 
- All pages use the same `<Table />` component, do we need to test pagination for each validation type (syntax errors, logic errors, warnings)?
- Verifies navigation of paginated results on the Logic errors page
1. Run Playwright test: `filing-app` -> `upload-file` -> `completeUploadLogicErrors.spec.ts`

[e2e] (uploadFile) Navigate paginated results

---

src/pages/Filing/FilingApp/InstitutionHeading.tsx

Fixed a bug that was causing one space to appear instead of the intended two.
- src
- pages
- Filing
- FilingApp
- InsitutionHeading.tsx: Replaced double spaces with double unicode non-breaking spaces.
1. Pull the branch
2. Relaunch whatever is necessary
3. Navigate to a page in the app that contains the Filing Steps and the Institution Heading
4. Verify that the pipe character is surrounded by two spaces in the Institution Heading. The attached screenshot has a red box which surrounds the area to check.

[Bug] InstitutionHeading Pipe Spacing Fix

---

e2e/example.spec.demo.ts
e2e/fixtures/testFixture.ts
e2e/pages/filing-app/formAlerts.spec.ts

Was looking at [this PR](https://github.com/cfpb/sbl-frontend/pull/988) and noticed some test failures. Fixes some e2e test failures that arose from the recent phone extension v2 changes.
- changes extension -> phone extension
- updates error text
1. Tests are now passing, check out the screenshots.
**Before**
**After**
- Lots could be done to import some of these expected strings, but this should fix our issues for now.

fix(e2e): account for phone extension changes

---

e2e/example.spec.demo.ts
e2e/fixtures/testFixture.ts
e2e/pages/filing-app/complete-user-profile/checkCupFormErrors.spec.ts
e2e/pages/filing-app/filing-step-routing/_shared.ts
e2e/pages/filing-app/filing-step-routing/errorsLogic.spec.ts
e2e/pages/filing-app/filing-step-routing/errorsSyntax.spec.ts
e2e/pages/filing-app/filing-step-routing/noUpload.spec.ts
e2e/pages/filing-app/filing-step-routing/pointOfContact.spec.ts
e2e/pages/filing-app/filing-step-routing/warnings.spec.ts
e2e/pages/filing-app/formAlerts.spec.ts
e2e/pages/filing-app/point-of-contact/checkPocFormErrors.spec.ts
e2e/pages/filing-app/sign-and-submit/completeFilingFlowWithOnlyWarnings.spec.ts
e2e/pages/filing-app/unavailableApis.spec.ts
e2e/pages/filing-app/uploadFile/completeUploadLogicErrors.spec.ts
e2e/pages/filing-app/uploadFile/completeUploadSyntaxErrors.spec.ts
e2e/pages/shared-lending-platform/InstitutionProfile.spec.ts
e2e/pages/shared-lending-platform/Navigation.spec.ts
e2e/pages/shared-lending-platform/NonAssociatedUserProfile.spec.ts
e2e/pages/shared-lending-platform/UpdateInstitutionProfile.spec.ts
e2e/pages/shared-lending-platform/UserProfile.spec.ts
e2e/pages/shared-lending-platform/unauthenticated-homepage/DeniedDomain.spec.ts
e2e/pages/shared-lending-platform/unauthenticated-homepage/paperworkReductionAct.spec.ts
e2e/pages/shared-lending-platform/unauthenticated-homepage/privacyNotice.spec.ts
e2e/utils/blockApi.ts
e2e/utils/navigation.utils.ts
e2e/utils/uploadFile.ts
playwright.config.ts

Adjusted timeouts to make e2e tests run consistently with up to 4 workers.
- Added explicit timeouts to the playwright configuration
- Test Suite Timeout of 1 Hour
- Individual Test Timeout of 5 Minutes
- Expect Timeout of 60 Seconds
- Removed individual expect timeouts from tests
- Removed test.slow calls
- Removed test.setTimeout calls
- Created functions for clicking the 'continue' and 'continue to next step' buttons
- Allowed the continue to next function to explicitly wait before clicking the button
- This was a large part of the fix and as such these functions should be used in the future
- Replaced all instances of clicking 'Continue' and 'Continue to next step' buttons with the new functions
1. Pull the branch
2. Restart the stack if necessary
3. From within the sbl-frontend …

[e2e] Investigate performance issues

---

src/pages/Filing/ViewInstitutionProfile/index.tsx

Closes #1030 
- Render page-level error alert for API errors, as opposed to rendering a separate `500` page
1. Block API requests from the following source in Chrome dev tools:
1. `localhost:8881/v1/institutions/123456789TESTBANK123`
2. Visit http://localhost:8899/institution/123456789TESTBANK123
3. Observe that things reflect the screenshot below.

[Institution profile] Page-level error for API issues

---

Dockerfile
src/App.tsx
src/constants/release.json

Close #1044 
Note: Generation of the `DOCKER_TAG` build-arg is built into the SBL CLI
- Displays the provided "version" tag at the bottom of each page
1. Include the desired display tag in your Docker `build` command: `--build-arg DOCKER_TAG=1044-show-tag`
2. Verify it is displayed at the bottom of the page

feat: Display Docker image tag in app Footer to help identify deployed changes

---

e2e/fixtures/testFixture.ts
e2e/pages/shared-lending-platform/NonAssociatedUserProfile.spec.ts
e2e/pages/shared-lending-platform/UserProfile.spec.ts
e2e/pages/shared-lending-platform/unauthenticated-homepage/NavMenu.spec.ts
src/utils/useHeaderAuthLinks.tsx

Adding additional logic to configure what navbar options are available and under what circumstances they appear
- Updated the navbar links logic so that it shows the correct links on the correct pages
- Added e2e test logic to validate that the navbar is configured correctly in a few different places
1. Verify that the pipeline is passing
2. Pull the branch
3. Launch/releaunch the stack as necessary
4. Access the non authenticated landing page
5. Verify that there are no navbar options
6. Login as an non-associated user
7. Verify that only the the logout nav option appears
8. Login as a full associated user
9. Navigate to the home page
10. Verify that the full nav options appear

Nav Menu Presentation

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/push.yml
.github/workflows/test.yml

*** need to merge [sbl-project pr](https://github.com/cfpb/sbl-project/pull/331) prior to mergeing this one ***
- adding workflow for build and publish images to GHCR
- updated current pattern to include new workflow

add build and publish workflow
