- buildspec.yml
Due to limitations on how we pass in ECR information, dynamically set the ECR URL based on the account the Codebuild project is running.
- Dynamically set the ECR repository
- Correct yaml
> Update buildspec with ECR handling

- src/api/axiosService.ts
- src/api/common.ts
- src/api/requests/submitUpdateFinancialProfile.ts
- src/api/requests/submitUserProfileFi.ts
- src/pages/ProfileForm/CreateProfileForm/index.tsx
Just testing out @shindigira's good PR over here on AWS, and I was hitting some CORS errors. Talked with @jcadam14 a bit, and I think removing the custom headers on the `POST` will as Alex would say "feed two birds with one scone."
1. We don't need these custom headers anymore (user info is pulled from keycloak and the subject line is handled by the backend)
2. [CORS woes](https://github.com/cfpb/regtech-mail-api/blob/1b6651c1b661ffd1d7cc4293e25c7c793a8fa392/regtech_mail_api/api.py#L32)
It's possible we'll want to re-introduce custom headers for something (maybe user name for the Complete User Profile, if we don't go the route of updating it in Keycloak first), but for now we don't need them.
Closes #270 
- removes unnecessary headers causing CORS issues
I set up the institutions db / …
> fix(cors): fix cors / remove headers no longer needed

- README.md
- package.json
- start.sh
Closes #298 
1. Pending: Need a fix in `sbl-project` that is currently preventing `create_institutions.sh` from successfully running
1. ~Pending: https://github.com/cfpb/sbl-project/pull/165~
1. In sbl-frontend run: `yarn seed`
3. Mock Institutions and Filing Period should be created
> Add a `yarn seed` script to run mock data generation scripts

- src/pages/Filing/ViewUserProfile/UserInformation.tsx
Part of #317
- Prevent crash
- Make note to figure out why the API changed (will do that in #317)
- Visit http://localhost:8899/profile/view
- Profit 💰
> [User Profile] Temp fix to avoid crash

- src/components/StepIndicator.tsx
Closes #323
Changes, identified while building the demo, that we want to keep from that PR.
> [StepIndicator] Render `Current` step label in bold text

- README.md
- package.json
Closes #376
Easy command to run Cypress against local without changing ENV vars or config files
- Add script
- Update README
1. yarn test:e2e:headless:local
> Yarn script - Run Cypress headlessly against local dev

- src/pages/Filing/FilingApp/FilingSubmit.helpers.tsx
- src/types/filingTypes.ts
Close #450 
1. Upload `logic-warnings_small.csv`
2. Navigate to the Sign & submit page
3. Observe that `Confirm your register information` => `Total loans/applications` => 7
> feat: [Sign and submit] Render total SBLAR record count

- src/pages/AuthenticatedLanding/FileSbl.tsx
Close #615 
- Render "File your data" button
1. Visit http://localhost:8899/landing
2. Confirm button + text
> fix: [Filing landing] "File your data" button

- src/pages/Filing/PaperworkNotice.tsx
- src/pages/Filing/PrivacyNotice.tsx
Close #617 
- Content updates
1. http://localhost:8899/paperwork-reduction-act-notice
2. http://localhost:8899/privacy-act-notice
|Paperwork|Privacy|
|---|---|
|![Screenshot 2024-05-30 at 3 02 24 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/363327b9-897f-43dd-89ea-8b51097bd883)|![Screenshot 2024-05-30 at 3 02 10 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/5625da8f-719a-4743-a292-072c77786f71)|
> Paperwork and Privacy notice content

- src/pages/Filing/FilingHome.tsx
Close #613 
- Updated sidebar `PRIVACY ACT` content
1. Visit http://localhost:8899/
2. Confirm sidebar content
> fix: [FilingHome] Update sidebar content

- src/pages/Filing/FilingApp/FilingFieldLinks.tsx
- src/pages/Filing/FilingApp/FilingOverviewPage.tsx
- src/pages/Filing/FilingApp/InstitutionCard.helpers.ts
Close #620 
Filing home
- Update content for `Start the filing process` card
- Add comma after "specifications"
|Before|After|
|---|---|
|![before](https://github.com/cfpb/sbl-frontend/assets/2592907/12058954-cfc8-4e6b-a0f2-21641221c038)|![after](https://github.com/cfpb/sbl-frontend/assets/2592907/15eb18f1-723f-4594-9bde-f456ed4d6a6d)|
||![Screenshot 2024-05-31 at 10 19 29 AM](https://github.com/cfpb/sbl-frontend/assets/2592907/47dc514a-9488-4859-b1e7-698410652de1)|
Upload file
- Add comma after "specifications"
- Downcase link text
|Before|After|
|---|---|
|![Screenshot 2024-05-31 at 10 23 26 AM](https://github.com/cfpb/sbl-frontend/assets/2592907/7704eed4-372e-4537-ab45-9a22e3469879)|![Screenshot 2024-05-31 at 10 23 46 AM](https://github.com/cfpb/sbl-frontend/assets/2592907/d04aab5f-6ada …
> Content updates

- src/pages/AuthenticatedLanding/FileSbl.tsx
> fix(authenticated landing): content update

- src/components/AssociatedInstitution.tsx
Close #655 
|before|after|
|---|---|
|![Screenshot 2024-06-06 at 2 51 27 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/0b363b07-779c-474a-9006-cec96a247931)|![Screenshot 2024-06-06 at 2 50 40 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/81333973-1517-45fe-a352-54f016443f20)|
Also applies to `View user profile`
> [Associated institutions] Remove icon

- src/pages/ProfileForm/Step1Form/Step1FormInfoFieldGroup.tsx
- tailwind.config.js
Close #686 
- Add Tailwind color variable `grayDarker`
- Add Privacy Notice to Complete user profile pages (both with/without associated institution)
> [Complete profile] Add privacy notice

- index.html
For mvp, we just need to update the title and description to match our clearance docs and put a meta tag on the index telling crawlers not to index our beta site. After-mvp, I made https://github.com/cfpb/sbl-frontend/issues/701 for more SEO investigation post-mvp. Some of the accessibility changes that are coming will be adding unique titles to all the pages in a follow-up PR.
- placeholder title tag and description
- noindex tag added
1. Do the new updated title, description, and noindex tags appear in the `<head>`?
> feat(seo): basic title, description, nofollow

- src/pages/Filing/FilingApp/InstitutionHeading.tsx
Close #727
Based on a comment in the design file. 
|Before|After|
|---|---|
|![Screenshot 2024-06-18 at 3 09 05 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/2f391fec-6f8f-4fe9-91ab-dfcb8d66caff)|![Screenshot 2024-06-18 at 3 08 51 PM](https://github.com/cfpb/sbl-frontend/assets/2592907/e0de7565-3508-4ef0-9b8b-6342e9c6db1d)|
> fix: [Filing home] Institution cards - wrap long heading text

- src/pages/Filing/FilingApp/FilingSubmit.helpers.tsx
- src/pages/Filing/FilingApp/FilingSubmit.tsx
- src/types/filingTypes.ts
Close #722 
- Task: Update top warning alert content
- Task: Update bottom success alert content
- Fix: Source for Warning/Error counts
Compare against the design file
|Time|Screenshot|
|---|---|
|Before|![Screenshot 2024-06-18 at 9 56 10 AM](https://github.com/cfpb/sbl-frontend/assets/2592907/e4970b51-8a3f-4f2b-b2cf-eb8cf60726fc)|
|After|![Screenshot 2024-06-18 at 9 56 38 AM](https://github.com/cfpb/sbl-frontend/assets/2592907/0b8c4592-af68-4281-b48f-af69dc656eca)|
> fix: [Sign & submit] Content updates and bug fixes

- buildspec.yml
This change brings back container image scanning.
> ci: readd-image-scan

- buildspec.yml
Turning image scanning back off.
> ci: turn scanning back off

- .github/CODEOWNERS
Adds @ojbravo to our codeowners file for easier code review. Welcome again to the team Omar!
- add @ojbravo to CODEOWNERS
1. Next PR, he should be automatically added to the reviewers
> chore(codeowners): add Omar to codeowners file

- src/pages/PointOfContact/index.tsx
Close #759
|Before|After|
|---|---|
|![before](https://github.com/cfpb/sbl-frontend/assets/2592907/8adafb05-56dd-463a-a287-7df75911a1d2)|![after](https://github.com/cfpb/sbl-frontend/assets/2592907/9a19fc3d-0815-4664-91cf-37a87be935a4)|
> [Point of contact] Correct width of privacy notice text

- src/pages/Filing/FilingApp/InstitutionCard.helpers.ts
- removes one more instance of "for submission" as per Natalia's feedback
1. Does the diff show that "for submission" has been removed?
> fix(content): remove one more instance of "submission"

- README.md
- start.sh
- adds the new `regtech-cleanup-api` to `start.sh` and the README.md
1. Try running `yarn update` and see if it works now on checking and updating `regtech-cleanup-api`
> fix(start.sh): add regtech-cleanup-api

- README.md
- update node version in readme
> fix(readme): update node version required

- .github/CODEOWNERS
- remove ojbravo and shindigira from codeowners file
> chore(codeowners): remove ojbravo and shindigira

- .github/workflows/push.yml
- .github/workflows/test.yml
need to build local sbl-frontend on merge for tests regardless of use_release_images flag.
> add condition to fix push workflow
